### ISSUE TITLE
wrong tid calculation

### ISSUE THREAD

**Issue by ael-code** [HPDCS/ROOT-Sim#32]
the thread id should be unique even in a distributed system with more then one kernel.

At the moment the tid is calculated in the `__helper_create_thread()` as a function of `local_tid` and `kid`. The used function is the following:
```c
tid = (kid << (sizeof(unsigned int) * 8 / 2)) | local_tid;
```
with two kernels and two threads I get the following run:
```c
[kid: 1, local_tid: 1] -> tid: 65537
```

**Comment by alessandropellegrini** [comment]
The `kid << (sizeof(unsigned int) * 8 / 2)` part was meant exactly to have different tids on different kernels, although non-contiguous. This should be ok nevertheless. Why is this wrong?
