### ISSUE TITLE
missing dependencies list

### ISSUE THREAD

**Issue by ael-code** [HPDCS/ROOT-Sim#4]
The installation process is a bit tricky, there is no dependencies list on the `README`.
You need to find out which package you miss launching multiple time `autogen.sh` and looking at the errors.

It will be nice to have a dependencies list for some major distributions like debian/ubuntu etc..

On debian stable the compilation seems to required:

```
autotools-dev
automake
libtool ( libtoolize )
```

**Comment by alessandropellegrini** [comment]
That's quite common stuff to use when dealing with autotools, as stated in `README`. Anyhow, for the sake of clarity, I've updated the `README`.
