### ISSUE TITLE
missing sorting direction for list datatypes

### ISSUE THREAD

**Issue by ael-code** [HPDCS/ROOT-Sim#40]
the `__list_place` function exposed by the list datatype module allow to use the linked list as an ordered queue. The problem is that is not specified anywhere which is the sort direction.

Reading the code I concluded that:
element are sorted in increasing order from `head` to `tail`.
`head` -> min value
`tail` -> max value

**Comment by alessandropellegrini** [comment]
This is true that it's not specified, and it's true as well that elements are sorted increasingly.
There is no actual need to alter the ordering direction, as you have both `head` and `tail`, and you can navigate in both directions.
Could it be solved only by documenting this feature?
