### ISSUE TITLE
ignored mmap errors

### ISSUE THREAD

**Issue by ael-code** [HPDCS/ROOT-Sim#56]
errors raised on `mmap` calls on allocator initialization are ignored:

#### error stack trace:
- [`mmap` - src/mm/allocator.c:63](https://github.com/HPDCS/ROOT-Sim/blob/develop/src/mm/allocator.c#L63)
- [`allocate_pages` - src/mm/allocator.c:271](https://github.com/HPDCS/ROOT-Sim/blob/develop/src/mm/allocator.c#L271)
- [`allocate_mdt` - src/mm/allocator.c:340](https://github.com/HPDCS/ROOT-Sim/blob/develop/src/mm/allocator.c#L340)
- [`allocator_init` - src/mm/dymelor.c:41](https://github.com/HPDCS/ROOT-Sim/blob/develop/src/mm/dymelor.c#L41)

**Comment by alessandropellegrini** [comment]
This was silently fixed in d868a3af9d52661f9be2ab63268cf3d2f21e4c2f.

Yet, the fix is partial as the code will flow across `rootsim_error()`. This is related to #12.

I consider anyhow this fixed, as soon as #12 is fixed, the requested behaviour will work.
