### ISSUE TITLE
do we still need to update `min_in_transit`?

### ISSUE THREAD

**Issue by ael-code** [HPDCS/ROOT-Sim#61]
Looking at the code I was wondering if it is still necessary to store the minimum timestamp of buffered messages into the outgoing queue. At least for the GVT calculation it shouldn't be necessary.

https://github.com/HPDCS/ROOT-Sim/blob/5e1487dd1063a709a5ba2fe09827f885ed24ec82/src/communication/communication.c#L339-L341

Maybe I'm wrong :)

**Comment by alessandropellegrini** [comment]
Not anymore!
This was used by the `timestretch` branch which will be eventually integrated into the `develop` branch. yet, along time, this has been superseded by different facilities which are later used in this module:

https://github.com/HPDCS/ROOT-Sim/blob/timestretch/src/scheduler/preempt_callback.S#L75

So this will be removed.
