### ISSUE TITLE
Messages are validated twice

### ISSUE THREAD

**Issue by ael-code** [HPDCS/ROOT-Sim#73]
Initially the message is validate in the `Send()` function: https://github.com/HPDCS/ROOT-Sim/blob/c98ac1d0cf59322f324fde065b620341fe737053/src/communication/communication.c#L274

Then it will be validated as well in the subsequent call `insert_bottom_half()`: https://github.com/HPDCS/ROOT-Sim/blob/c98ac1d0cf59322f324fde065b620341fe737053/src/queues/queues.c#L134

**Comment by alessandropellegrini** [comment]
There was an ancillary reason to this: a message coming from a remote node doesn't pass locally through `Send()`, so we can only make a (local) check in `insert_bottom_half()`.
It could be safe however to drop the one in `Send()`.
Anyhow, with no `--enable-debug` at configure time, these calls are mapped to no-op, so they won't harm much performance in the end.

**Comment by alessandropellegrini** [comment]
I'd keep this open, as anything which can help tidying the code is useful, just as a future reference.

**Comment by alessandropellegrini** [comment]
This can be considered as closed, although it's not yet merged in `develop`.
