### ISSUE TITLE
Numa submodule make implicit function declaration:

### ISSUE THREAD

**Issue by ael-code** [HPDCS/ROOT-Sim#79]
```
mm/buddy.c: In function ‘allocator_init’:
mm/buddy.c:259:2: warning: implicit declaration of function ‘numa_init’; did you mean ‘ecs_init’? [-Wimplicit-function-declaration]
  numa_init();
  ^~~~~~~~~
```

**Comment by alessandropellegrini** [comment]
Thanks. I'll temporarily disable the numa subsystem in the 2.0.0 release, as it requires a significant re-engineering after the work we're doing with @StefanoConoci.
This will be reintroduced in a future release.
