### ISSUE TITLE
Inform Valgrind about ULT stacks

### ISSUE THREAD

**Issue by ael-code** [HPDCS/ROOT-Sim#97]
In order to be able to use valgrind with ULT enabled it is necessary to inform the Valgrind runtime about the creation/destruction of their stacks.

Some useful resources:
 - [valgrind.h](https://sourceware.org/git/?p=valgrind.git;a=blob;f=include/valgrind.h;h=577c8f05e5b02ea8f332d43b6d24b30c248f4eb1;hb=HEAD#l6571)  haeder that expose the VALGRIND_REGISTER_STACK routine
 - Official [valgrind docs](valgrind.org/docs/manual/manual-core-adv.html), in particular section `3.1. The Client Request mechanism`
 - [Argobots implementation](https://github.com/carns/argobots/blob/4a84e66ed8544db215d6862f527775387418f7f6/src/mem/valgrind.c#L32) of valgrind stack registering

**Comment by alessandropellegrini** [comment]
Non-relevant, as ULTs have been removed in v3.0.0
